version: '3.7'

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
    - ./modpacks:/modpacks:ro
    environment:
      EULA: "true"
      ONLINE_MODE: "false"
      MEMORY: '10G'
      LEVEL_TYPE: "BIOMESOP"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: https://media.forgecdn.net/files/3157/836/aezirro.server_v1.0.0.zip
    tty: true
    restart: 'unless-stopped'
    ports:
      - 25565:25565