version: '3.7'

# Light version of docker-compose dedicated for small deployments to play with friends.

services:
  minecraft:
    image: itzg/minecraft-server
    environment:
    
      # Server Meta-Configuration
      EULA: "true"
      ONLINE_MODE: "false"
      SERVER_NAME: "The Mighty Alchemist's Quest"
      DIFFICULTY: "hard"
      OPS: "ziqiln"
      MOTD: "\u00a76Quest of Mighty Alchemist\u2122\u00a7r, Community Beta Server\nRrelease \u00a790.0.1-alpha.11 \u00a7rby \u00a7kziqiln\u00a7r\n\n"
      # ICON: <URL>
      MAX_PLAYERS: 1337
    
      # Performance Configuration
      ENABLE_AUTOPAUSE: "true"
      MAX_TICK_TIME: "10"
      MAX_MEMORY: '3G'
      USE_AIKAR_FLAGS: 'false'

      # World Configuration
      LEVEL_TYPE: "BIOMESOP"
      SEED: "7964 109 5940"
      
      # Server Mode
      TYPE: CURSEFORGE
      CF_SERVER_MOD: https://github.com/ZiQiLN/mystic-alchemists/releases/download/v0.0.1-alpha.12/MAS-0.0.1-alpha.12.zip
      
      # RCON
      # ENABLE_RCON: "true"
      # RCON_PASSWORD: "testing"
      # RCON_PORT: 28016

      # Utility Configuration
      REMOVE_OLD_MODS: "true"
    
    tty: true
    restart: 'unless-stopped'
    ports:
      - 25565:25565
    volumes:
      - "minecraft-data:/data"
  
  # rcon:
  #   image: itzg/rcon
  #   ports:
  #     - "4326:4326"
  #     - "4327:4327"
  #   volumes:
  #     - "rcon:/opt/rcon-web-admin/db"

volumes:
  minecraft-data: {}
  # rcon: {}