version: '3.7'

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
    - ./modpacks:/modpacks:ro
    environment:
      EULA: "true"
      ONLINE_MODE: "false"
      MEMORY: '6G'
      LEVEL_TYPE: "BIOMESOP"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: https://media.forgecdn.net/files/3158/95/MA-master-605e2c5.460869203.zip
    tty: true
    restart: 'unless-stopped'
    ports:
      - 25565:25565