version: '3.7'

# Production-ready docker-compose file for solutions that prefer usage of Docker instead Kubernetes.
# However, I would like to recommend Kubernetes when using Bungeecord.

services:

  # Core Minecraft Server Service

  minecraft:
    image: itzg/minecraft-server
    environment:
    
      # Server Meta-Configuration
      EULA: "true"
      ONLINE_MODE: "false"
      SERVER_NAME: "The Mighty Alchemist's Quest"
      DIFFICULTY: "hard"
      OPS: "ziqiln"
      MOTD: \u00a76Quest of Mighty Alchemist\u2122\u00a7r, Community Beta Server\nRrelease \u00a790.0.1-alpha.11 \u00a7rby \u00a7kziqiln\u00a7r\n\n\∂
      ICON: 'https://media.forgecdn.net/avatars/thumbnails/328/753/64/64/637453258681382386.png'
      MAX_PLAYERS: 1337
    
      # Performance Configuration
      ENABLE_AUTOPAUSE: "true"
      MAX_TICK_TIME: "35"
      MAX_MEMORY: '6G'
      USE_AIKAR_FLAGS: 'false'

      # World Configuration
      LEVEL_TYPE: "BIOMESOP"
      SEED: "7964 109 5940"
      
      # Server Mode
      TYPE: CURSEFORGE
      CF_SERVER_MOD: 'https://media.forgecdn.net/files/3161/198/MAS-0.0.1-alpha.12.1.zip'
      CF_BASE_DIR: /data
      
      # Utility Configuration
      REMOVE_OLD_MODS: "true"
    
    tty: true
    restart: 'unless-stopped'
    ports:
      - 25565:25565
    volumes:
      - "mc-data:/data"

  # bungeecord:
  #   image: itzg/bungeecord

volumes:
  mc-data: {}