# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
    jira: circleci/jira@1.3.0

jobs:
    release:
        docker:
            - image: cimg/node:15.6.0
        steps:
            - checkout
            - run: yarn
            - run: node scripts/10-preparePackage.js
            - run: yarn run semantic-release

    # Builds package and stores artifact, which can be used in another jobs.
    build:
        docker:
            - image: 'circleci/node:12'
        steps:
            - checkout
            - run: yarn
            - run: node scripts/10-preparePackage.js
            - store_artifacts:
                  path: ~/project/dist/curseprofile.zip
                  destination: kubick.zip
workflows:
    nighly:
        jobs:
            - build
            - release:
                  requires:
                      - 'build'
                  post-steps:
                      - jira/notify
        triggers:
            - schedule:
                  cron: '30 12 * * FRI'
                  filters:
                      branches:
                          only:
                              - master
                              - beta
