# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  jira: circleci/jira@1.3.0

jobs:
  release:
    docker:
      - image: "circleci/node:10"
    steps:
      - checkout
      - run: yarn
      - run: node scripts/pack.js
      - store_artifacts:
          path: /project/dist/curseprofile.zip
          destination: kubick.zip
      - run: yarn semantic-release

workflows:
  release:
    jobs:
      - release:
          post-steps:
            - jira/notify
