_specver: 2

modpack:
  name: The Mystic Alchemist's Modpack
  description: ...

install:
  mcVersion: 1.12.2

  loaderVersion: null

  installerUrl: http://files.minecraftforge.net/maven/net/minecraftforge/forge/{{@mcversion@}}-{{@loaderversion@}}/forge-{{@mcversion@}}-{{@loaderversion@}}-installer.jar

  installerArguments:
    - "--installServer"

  modpackUrl: https://media.forgecdn.net/files/3158/674/MA-461994521.zip
  modpackFormat: curse

  # Settings which are specific to the format used, might not be needed in some casese
  formatSpecific:
    # optional paramenter used for curse to specify a whole project to ignore (mostly if it is client side only)
    ignoreProject:
      - 231275 # Ding
      - 238222 # Just Enough Items (JEI)
      - 229302 # Custom Loading Screen
      - 292785 # VanillaFix
      - 238372 # Neat
      - 253449 # Hwyla
      - 224712 # Wawla
      - 32274 # JourneyMap
      - 60089 # Mouse Tweaks
      - 248787 # AppleSkin
      - 238891 # Dynamic Surroundings
      - 309318 # Dynamic Surroundings: HUD
      - 366140 # Dynamic View
      - 297038 # CraftPresence
      - 306549 # Tips
      - 306187 # Featured Servers
      - 228529 # Better Foliage
      - 248453 # Shadowfacts' Forgelin (Better Foliage Library)
      - 308702 #Mod Menu
      - 313219 #Health Overlay
      - 317514 #Mouse Wheelie
      - 325492 #Light Overlay
      - 325625 #Roughly Enough Resources
      - 335493 #Dynamic FPS
      - 353641 #JumpOverFences
      - 354047 #Ok Zoomer
      - 355583 #Advancements Enlarger
      - 360449 #Egg Tab
      - 361550 #No Potion Offset
      - 363126 #Boring Backgrounds
      - 365521 #Pling
      - 366240 #GameInfo
      - 369122 #Better Enchanted Books
      - 380393 #'Slight' Gui Modifications
      - 388252 #Notes
      - 398502 #Cherished Worlds
      - 400929 #cAn i MiNe thIS bLOCk?
      - 401978 #Disable Custom Worlds Advice
      - 408366 #SlotLock
      - 411705 #Damage Tilt

  baseInstallPath: ~

  ignoreFiles:
    - mods/optifine*.jar
    - resources/**

  additionalFiles:
  localFiles: ~
  checkFolder: yes
  installLoader: yes
  spongeBootstrapper: https://github.com/simon816/SpongeBootstrap/releases/download/v0.7.1/SpongeBootstrap-0.7.1.jar

launch:
  ramDisk: no
  checkOffline: no
  maxRam: 6G
  autoRestart: yes
  crashLimit: 10
  crashTimer: 60min
  preJavaArgs: ~
  startFile: forge-{{@mcversion@}}-{{@loaderversion@}}-universal.jar
  forcedJavaPath: ~
  javaArgs:
    - "-XX:+UseG1GC"
    - "-XX:+ParallelRefProcEnabled"
    - "-XX:MaxGCPauseMillis=30"
    - "-XX:+UnlockExperimentalVMOptions"
    - "-XX:+DisableExplicitGC"
    - "-XX:+AlwaysPreTouch"
    - "-XX:G1NewSizePercent=30"
    - "-XX:G1MaxNewSizePercent=40"
    - "-XX:G1HeapRegionSize=8M"
    - "-XX:G1ReservePercent=25"
    - "-XX:G1HeapWastePercent=5"
    - "-XX:G1MixedGCCountTarget=4"
    - "-XX:InitiatingHeapOccupancyPercent=15"
    - "-XX:G1MixedGCLiveThresholdPercent=90"
    - "-XX:G1RSetUpdatingPauseTimePercent=5"
    - "-XX:SurvivorRatio=32"
    - "-XX:+PerfDisableSharedMem"
    - "-XX:MaxTenuringThreshold=1"
    - "-Dusing.aikars.flags=https://mcflags.emc.gs"
    - "-Daikars.new.flags=true"
    - "-XX:ConcGCThreads=3"
    - "-XX:ParallelGCThreads=12"