_specver: 2

modpack:
  name: Aezirro
  description: ...

install:
  mcVersion: 1.16.4

  loaderVersion: 0.10.8

  installerUrl: https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.5.2.40/fabric-installer-0.5.2.40.jar

  installerArguments:
    - "server"
    - "-downloadMinecraft"
    - "-snapshot"
    - "-mcversion"
    - "1.16.4"
    - "-loader"
    - "0.10.8"

  # Link to where the file where the modpack can be distributed
  # This supports loading from local files as well for most pack types if there is file://{PathToFile} in the beginning
  modpackUrl: https://www.curseforge.com/minecraft/modpacks/mystic-alchemists/download/3157823
  
  # This is used to specify in which format the modpack is distributed, the server launcher has to handle each individually if their format differs
  # current supported formats:
  # - curseforge or curse
  # - curseid
  # - zip or zipfile
  modpackFormat: curse

  # Settings which are specific to the format used, might not be needed in some casese
  formatSpecific:
    # optional paramenter used for curse to specify a whole project to ignore (mostly if it is client side only)
    ignoreProject:
      - 317514 #mouse wheelie
      - 411705 #damage tilt

  baseInstallPath: ~

  ignoreFiles:
    - mods/optifine*.jar
    - resources/**

  additionalFiles:
  localFiles: ~
  checkFolder: yes
  installLoader: yes
  spongeBootstrapper: https://github.com/simon816/SpongeBootstrap/releases/download/v0.7.1/SpongeBootstrap-0.7.1.jar

launch:
  spongefix: no
  ramDisk: no
  checkOffline: no
  maxRam: 4G
  autoRestart: yes
  crashLimit: 10
  crashTimer: 60min
  preJavaArgs: ~
  startFile: fabric-server-launch.jar
  forcedJavaPath: ~
  javaArgs:
    - "-server"
    - "-XX:+UseG1GC"
    - "-XX:+ParallelRefProcEnabled"
    - "-XX:MaxGCPauseMillis=100"
    - "-XX:+UnlockExperimentalVMOptions"
    - "-XX:+DisableExplicitGC"
    - "-XX:+AlwaysPreTouch"
    - "-XX:G1NewSizePercent=30"
    - "-XX:G1MaxNewSizePercent=40"
    - "-XX:G1HeapRegionSize=8M"
    - "-XX:G1ReservePercent=20"
    - "-XX:G1HeapWastePercent=5" 
    - "-XX:G1MixedGCCountTarget=4" 
    - "-XX:InitiatingHeapOccupancyPercent=15" 
    - "-XX:G1MixedGCLiveThresholdPercent=90" 
    - "-XX:G1RSetUpdatingPauseTimePercent=5" 
    - "-XX:SurvivorRatio=32" 
    - "-XX:+PerfDisableSharedMem" 
    - "-XX:MaxTenuringThreshold=1" 
    - "-Dusing.aikars.flags=https://mcflags.emc.gs" 
    - "-Daikars.new.flags=true"

